name: soireesafe
description: "SoireeSafe is a unique app that lets you rate and report on bars in Marseille, ensuring everyone has a fantastic and safe night out!"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  supabase_flutter: '>=1.10.0'
  maplibre_gl: 0.22.0
  url_launcher: ^6.0.0
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
